### ISSUE TITLE
Network Security Group Rules

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#12]
If it's not EXPOSE'd, block it.  This is a defense in depth strategy, and IPTables can be replaced directly with our own firewall if we can build it to be integrateable. 

I'm not even sure if this makes sense in Docker.

**Comment by m3thr1l** [comment]
I’m not sure either. But we can certainly try.

**Comment by zachChilders** [comment]
I'm like 90% sure that docker is already implementing iptables for its basic functionality.  Instead of focusing on that, we should look into the NSG rules.

**Comment by zachChilders** [comment]
I don't think we need this right now
