### ISSUE TITLE
Terraform Authentication Issue

### ISSUE THREAD

**Issue by m3thr1l** [zachChilders/just-add-water#17]
`Error: Error in function call

  on k8s.tf line 36, in resource "azurerm_kubernetes_cluster" "k8s":
  36:             key_data = "${file("${var.ssh_public_key}")}"
    |----------------
    | var.ssh_public_key is "~/.ssh/id_rsa.pub"

Call to function "file" failed: no file exists at /root/.ssh/id_rsa.pub.

05:04:22 [ X ] Plan terraform environment`

**Comment by zachChilders** [comment]
Part of #2
