### ISSUE TITLE
Pentesting

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#22]
Set up pentesting experiment leveraging hackerone/mics.

Should compare us vs baseline.

It may be valuable to compare today vs end of project

**Comment by hmc-berk** [comment]
Run Pen test prior to full pentester review.

**Comment by zachChilders** [comment]
We have Pascal signed up for 11/16 and Christian signed up for a week after.  @hmc-berk do we have actual work we need to do for this before they hit it?

**Comment by zachChilders** [comment]
Pascal and Christian both hit us.  Neither were able to get in, but after giving a password these are results of note:

- Able to access our DB via a wordpress secret (unavoidable, we can't fix this)
- Recommended using nginx #41 
- Could not pivot out of the container.
