### ISSUE TITLE
CLTC Funding

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#24]
We need money to run things in Azure

**Comment by lisnter** [comment]
I think I'm dumb and I don't see the discussion of how to submit our request in the capstone Slack channel.  Is it someplace else?

**Comment by zachChilders** [comment]
I think Lisa mentioned it a while ago, but it was likely just a contact at CLTC. They should know off hand who to go to.

**Comment by lisnter** [comment]
Created draft document.  Please review.

https://drive.google.com/file/d/1jPKomoznKUBeah-d5scNXgRcq7M7Zhm1/view?usp=sharing

**Comment by zachChilders** [comment]
Have we done everything for this?  Are we just waiting for Lisa to submit?
