### ISSUE TITLE
Docker Hardening

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#32]
We need to ensure that our Docker agent is hardened correctly.  `Bench` from docker looks like a great way to check we're doing the right things.  

We'll need to remote into a host and run this to see what needs to be done.

https://github.com/docker/docker-bench-security

**Comment by hmc-berk** [comment]
this looks interesting:  https://www.open-scap.org/resources/documentation/security-compliance-of-rhel7-docker-containers/

**Comment by hmc-berk** [comment]
Docker STIGS have moved non-public.  Will review these:
https://medium.com/@arseny.chernov/securing-devops-review-of-approaches-a801742630ca
https://news.ycombinator.com/item?id=16014404

**Comment by zachChilders** [comment]
Yikes!  The hosts are in no way hardened.

[audit.log](https://github.com/zachChilders/just-add-water/files/3655523/audit.log)

**Comment by zachChilders** [comment]
Potentially addressed by #81.  @cclifford3 to decide
