### ISSUE TITLE
Stakeholder template

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#38]
Please do the stakeholder template

**Comment by hmc-berk** [comment]
https://drive.google.com/file/d/0Byod4FQWeRCkLUxGdWJDak5yYURpOG5lUncwLVlIUjg3SG8w/view

**Comment by lisnter** [comment]
[StakeholderRegister.SBD.xlsx](https://github.com/zachChilders/just-add-water/files/3656455/StakeholderRegister.SBD.xlsx)

**Comment by lisnter** [comment]
Stakeholder document uploaded (I think).  Comments?  If not, Heather, please submit.  I can talk about it tomorrow.
