### ISSUE TITLE
App Startup

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#46]
Ensure Magento has zero startup.  Our current image can do it by running some docker exec command found here: https://github.com/alexcheng1982/docker-magento

If we want to move to a different magento image that already does that that's fine too, as long as we have a way to inject values into it so we can connect to our DB.

This is primarily docker focused and I'd think the best approach would be to get the container to run on a local machine - if it bootstraps there it will bootstrap in k8s.

**Comment by hmc-berk** [comment]
Add a default WP page
