### ISSUE TITLE
Configure and harden sample app within Magento

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#47]
Leverage the existing sample app within Magento so it does something real-ish.

First task is to use Magento-provided sample data; second task is to customize with our own (optional).

**Comment by lisnter** [comment]
Useful info

Download:
https://magento.com/tech-resources/download
Get the full release 2.3.2 with sample data

Install:
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/zip_install.html
https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html
For simplicities sake use the one-user option

alpine creds:  root/magento289

Install/configure apache
https://wiki.alpinelinux.org/wiki/Apache

Update repositories
https://wiki.alpinelinux.org/wiki/Enable_Community_Repository

Add PHP (will this work with Magento?)
https://wiki.alpinelinux.org/wiki/Setting_Up_Apache_with_PHP
apk add apache2 php5-apache2

Need the updated repositories for this?
https://www.cyberciti.biz/faq/10-alpine-linux-apk-command-examples/
apk add apache2 php7-apache2 php7-gd php7-mysqli

stop/start/restart
rc-service stop/start/restart apache2 (or whatever)

Put
< ? php
 phpinfo();
 ? >
in 
/var/www/localhost/htdocs/testphp.php
and open page in a browser
(extra spaces in code to avoid stripping by git)

Add MariaDB (MySQL - let's see if it works)
https://wiki.alpinelinux.org/wiki/MariaDB
apk add mariadb mariadb-client
rc-update add mariadb default
rc-service mariadb start
execute
/etc/init.d/mariadb setup (per instructions from first start)
after that mysqladmin should work

copy magento file to /var/www/localhost/htcdocs/magento2
export PATH=$PATH:/var/www/html/magento2/bin

should do secure install

**Comment by lisnter** [comment]
This is super helpful for Docker:
https://docs.docker.com/get-started

**Comment by lisnter** [comment]
All right.  So I have a super trivial Alpine image.  I would have liked to use the
  FROM scratch
feature but I think using the existing Alpine Docker image is a better use of time.  So, here's the Dockerfile so far:
  FROM alpine:3.7

Magnificent, isn't it!!!

Then run
docker run -i -t --rm -p 4000:80 alpinetest

Which means -i interactive; -t open a tty; --rm remove when done; -p port mapping

**Comment by zachChilders** [comment]
Once the alpine image can run magento, please push it to the new org in its own repo.

**Comment by zachChilders** [comment]
I think this is actually done for the scope of this issue.  Please reopen if I'm wrong :)
