### ISSUE TITLE
Write summary for MACH37

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#50]
Per Lisa's note in the capstone slack channel.

**Comment by lisnter** [comment]
Document created (based on budget).
https://drive.google.com/file/d/15A2CLqy1Qo3Ck07QnlARX_md5GxdO3ey/view?usp=sharing

**Comment by lisnter** [comment]
New link.
https://drive.google.com/file/d/15A2CLqy1Qo3Ck07QnlARX_md5GxdO3ey/view?usp=sharing

**Comment by zachChilders** [comment]
Great work T!

**Comment by lisnter** [comment]
Thanks.  Completed and sent to MACH37.  They have replied:
"Quick question, in their request I notice that they state they are looking for guidance on how to continue to pursue the opportunity post Capstone - by that, do they mean that they intend to incorporate and go forth as a startup?"

To which we responded:
Hi Lisa Ho.  If you could relay to Jason that we are interested in seeing what can be done, that'd be great.  We're all pretty much in a place where the startup-life would be difficult (family, mortgage, etc.) but it would be cool to see what all the options he can envision.  We are excited to hear what he thinks about the project overall and our options.  We would love to have a conversation with his team.

No follow-up since Tuesday.
