### ISSUE TITLE
Add WordPress (in Alpine) instance

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#52]

**Comment by hmc-berk** [comment]
Run these command line until integration with TF.   Setup environment variables:

export WORDPRESS_DB_HOST='db'
export WORDPRESS_DB_USER='wpuser'
export WORDPRESS_DB_PASSWORD='wpuserpw'
export WORDPRESS_DB_NAME='wpdb'
export MYSQL_USER=$WORDPRESS_DB_USER
export MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD
export MYSQL_DATABASE=$WORDPRESS_DB_HOST
export MYSQL_RANDOM_ROOT_PASSWORD=1
