### ISSUE TITLE
Consider use of SCONE

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#54]
I read the beginning of this for week 7 and it seems intriguing.  We should evaluate and consider for phase 2 (post December).

Protects containers.

https://www.usenix.org/system/files/conference/osdi16/osdi16-arnautov.pdf

[Week7.SCONE.osdi16-arnautov.pdf](https://github.com/zachChilders/just-add-water/files/3710686/Week7.SCONE.osdi16-arnautov.pdf)

**Comment by zachChilders** [comment]
Seems like a good thing on paper.  Do you know if we can get ahold of it? 

Two considerations:
- They are a kernel module, which means we're modifying the underlying Linux host _image_, which is an expensive pipeline to maintain (but not unreasonable).
- They are Intel specific, which precludes usage on ARM based servers - those don't exist yet in any way we care about, but I've heard talk of multiple clouds moving that way eventually.

**Comment by zachChilders** [comment]
I think this isn't practical currently, because we'd need to add an entire pipeline for baking out VM images.  I'm going to close this for now, but we can revisit in the future.
