### ISSUE TITLE
Consider licensing model

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#55]
We should have a plan of how we want to license this prior to the end of the semester.  We don't necessarily need to release it right away but I think it would be good to consider what we want to do.  This is a key topic for our MACH37 conversations.  Since we're using lots of open-source material our hands are tied somewhat, right, but there are still options.

**Comment by zachChilders** [comment]
We're currently under BSD license.

**Comment by zachChilders** [comment]
Removing milestone to scope to actual deliverable work we need to do
