### ISSUE TITLE
Base Alpine

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#57]
Create Alpine Base image with LAMP dependencies.  Push into new repo in mics-sbd

**Comment by lisnter** [comment]
Some helpful links:
https://blog.iron.io/how-to-build-your-own-docker-images/

For apache2
https://stackoverflow.com/questions/48869833/alpine-unsatisfiable-constraints-missing-packages
https://wiki.alpinelinux.org/wiki/Apache

Add rc-service
apk add openrc

**Comment by lisnter** [comment]
Useful Docker:

docker build --no-cache -t alpinetest .
docker run -d --rm -p8000:80 -it alpinetest
docker ps
docker stop
docker exec -it (container name from docker ps) /bin/sh
curl 0.0.0.0:8000 (from host)
curl localhost:80(from container)

**Comment by lisnter** [comment]
OK.  Added to mics-sbd.  Use:
https://github.com/mics-sbd/alpine-lamp.git
to access it.
