### ISSUE TITLE
Add apache2 to normal init.d

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#61]
The docker file I (Terry) created starts apache directly which is fine but won't restart if it dies since it's not in init.  I tried installing and adding rc-service but it didn't seem to play nice with the rest of Alpine so I found the manual way to start it.

It would be better to add apache to the normal Alpine startup.

**Comment by zachChilders** [comment]
Do we still need this?

If apache dies, the whole container should probably die with it - it means your site is down on that container and kubernetes needs to take action to redeploy it.
