### ISSUE TITLE
Build secret service (Azure version)

### ISSUE THREAD

**Issue by lisnter** [zachChilders/just-add-water#65]
Build a web service that replies to:
/secret/<secret ID>
and returns
{
  "request":"<secret ID>"
  "secret":"<secret>"
  expiration?
  encoding?
  permissions?
  etc?
}

**Comment by lisnter** [comment]
`#
#  WhoGoesThere - web service to interface with Azure credentials store
#
#  Presents a single URL to retrieve the credentials associated with the provided key
#
import cherrypy

class SBDSecret( object ):

#  This is dumb but I can't figure out how to handle arguments after the url in the handler;
#  i.e.
#    /secret/mysecret?bad=news
#  WHY!!!!  
#  So, hook the pipeline before the handler and if there are any parameters the length will be >1
#  and just remove them.  Would be nice to force an error since the URL was malformed but this is
#  fine for now.
    @cherrypy.tools.register('before_handler')
    def handleArgs():
        if( len( cherrypy.request.params ) > 0 ):  #  some arguments on URL so remove them (?, ?=a, etc)
            cherrypy.request.params.clear()  #  empty it out


#  handle the URL without any argument or just /
    @cherrypy.expose
    @cherrypy.tools.handleArgs()
    @cherrypy.tools.json_out()
    def index( self ):
        return{ 'page':'index' }


#  handle anything that isn't handled via index() above or has any form that isn't
#  URL/secret/secretID which is captured below.  That means all url paths that are
#  *not* "secret/<something"
    @cherrypy.expose
    @cherrypy.tools.handleArgs()
    @cherrypy.tools.json_out()
    def default( self, *args ):
        return{ 'page':'default' }


#  Accept
#    URL:/secret/<secret ID>
#  which is valid and all forms of
#    URL:/secret/<secret ID>/anything else
#  all of which are invalid (so return an error)
    @cherrypy.expose
    @cherrypy.tools.handleArgs()
    @cherrypy.tools.json_out()
    def secret( self, secretID='none', *args ):  #  secretID='none' to catch if no secretID is provided
        if( len( args ) == 0 ):  #  if properly formed args will be ''
          return{ 'page':'secret no args %s and %s' % ( secretID, args ) }
        else:  #  anything else is an error
          return{ 'page':'secret with args %s and %s' % ( secretID, args ) }


if __name__ == '__main__':
    cherrypy.quickstart( SBDSecret() )

`

**Comment by lisnter** [comment]
[wgt4.zip](https://github.com/zachChilders/just-add-water/files/3760288/wgt4.zip)

Uploaded code as a zip file since github doesn't handle .py files?!?!

**Comment by zachChilders** [comment]
This should just be its own microservice repo.  It can go in mics-sbd unless you want it as a personal project forever :)

We won't need anything other than secret.

**Comment by zachChilders** [comment]
#41 depends on this

**Comment by zachChilders** [comment]
This was checked in last night.  Great work @lisnter!
