### ISSUE TITLE
Onboarding story

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/just-add-water#7]
What do organizations need to use this repo?  

Not automatable:
- Azure subscription
- AAD Tenant?

Automatable:
- Container Registry
- Terraform storage
- Master keyvault
- Service Principals

**Comment by hmc-berk** [comment]
My thought is that I'll network to engineering team SMEs at some interesting companies & have group conf calls that we can ask some preworked questions to round out our approach.  If you have target companies that you are intrigued by, lemme know.

**Comment by zachChilders** [comment]
Sounds like a good plan.  Even what we have can already handle the scale necessary for basically any company.  I'm concerned primarily with:

- Ergonomics:  This should be easy to use by standard IT staff regardless of their skillset.  If they can use a CLI, they should be able to deploy secure infrastructure using us.

- Support:  I don't have empirical data to support this - but I don't think most enterprises are Kubernetes ready.  We should aim to make migration to this platform as streamlined and automated as possible.  This could potentially be an "intermediate mode" where, for example, people are deploying IIS/Apache still.

**Comment by zachChilders** [comment]
This actually needs some formal docs, preferably hosted in the repo for discoverability

**Comment by zachChilders** [comment]
We can add docs in /docs and the site will pick it up
