### ISSUE TITLE
Disable IP Forwarding

### ISSUE THREAD

**Issue by hmc-berk** [zachChilders/just-add-water#70]
- IP forwarding on your virtual machine should be disabled (Preview)
- Secure transfer to storage accounts should be enabled - Secure transfer is an option that forces your storage account to accept requests only from secure connections (HTTPS). Use of HTTPS ensures authentication between the server and the service and protects data in transit from network layer attacks such as man-in-the-middle, eavesdropping, and session-hijacking.

**Comment by zachChilders** [comment]
Are we still flagging on this?  I think it might have been enabled for SSH access.

**Comment by zachChilders** [comment]
@hmc-berk was there a guide for this?

**Comment by hmc-berk** [comment]
No longer flagging on this.
