### ISSUE TITLE
Hardening via MFA

### ISSUE THREAD

**Issue by hmc-berk** [zachChilders/just-add-water#71]
MFA should be enabled on accounts with write permissions on your subscription
External accounts with write permissions should be removed from your subscription
There should be more than one owner assigned to your subscription
Diagnostic logs in Key Vault should be enabled

**Comment by zachChilders** [comment]
There's not going to be a way to automate this.  We should document the steps to do this.

**Comment by zachChilders** [comment]
Closed in #84
